
import React, { useState } from 'react';
import { SkinAnalysis } from '@/types';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { MessageSquare, FileText } from 'lucide-react';
import AIDoctorChat from '@/components/premium/AIDoctorChat';

interface DermatologistFeedbackProps {
  analysis: SkinAnalysis;
  premiumData: any;
  language?: 'en' | 'ar';
}

const DermatologistFeedback: React.FC<DermatologistFeedbackProps> = ({ 
  analysis, 
  premiumData,
  language = 'en'
}) => {
  // Doctor's analysis would be generated by an AI in a real app
  const doctorAnalysis = {
    en: {
      summary: `Based on the submitted images and AI analysis, I can see that you have combination skin with ${analysis.detectedIssues.join(', ')}. Your skin barrier appears slightly compromised, with signs of mild inflammation in certain areas.`,
      
      detailedAnalysis: `
        Your primary skin concerns appear to be related to moisture barrier function and mild inflammation. 
        The uneven texture and occasional breakouts suggest potential issues with cell turnover and possibly some follicular congestion.
        
        I notice that your skin's hydration level is slightly below optimal, which may be contributing to the increased oil production in the T-zone as the skin tries to compensate for the dehydration.
        
        The redness pattern is consistent with mild sensitivity, likely exacerbated by environmental factors rather than an underlying skin condition like rosacea. However, your skin's reaction is well within the range that can be effectively addressed with the right skincare regimen.
        
        Your skin's protective barrier function shows minor compromise based on the transepidermal water loss patterns evident in the analysis.
      `,
      
      possibleCauses: [
        "Environmental factors such as climate, pollution, or weather changes",
        "Hormonal fluctuations typical of your age demographic",
        "Potential reactivity to ingredients in current skincare products",
        "Lifestyle factors including stress, sleep quality, and dietary patterns",
        "Possible over-exfoliation or use of products that are too harsh for your skin type"
      ],
      
      recommendations: [
        "Focus on rebuilding your skin barrier with ceramide-rich products",
        "Introduce gentle chemical exfoliation 2-3 times weekly to address texture concerns",
        "Consider incorporating niacinamide to help regulate oil production and reduce inflammation",
        "Ensure consistent use of broad-spectrum SPF 30+ daily",
        "Include hydrating ingredients like hyaluronic acid and glycerin in your routine"
      ],
      
      productSuggestions: [
        {
          type: "Cleanser",
          description: "A gentle, non-stripping cleanser with a pH between 4.5-5.5 to maintain your skin's acid mantle",
          ingredients: "Look for cleansers containing glycerin, allantoin, or panthenol"
        },
        {
          type: "Treatment",
          description: "Consider a PHA or BHA product for gentle exfoliation and pore clearing",
          ingredients: "Gluconolactone (PHA) or 2% salicylic acid (BHA)"
        },
        {
          type: "Serum",
          description: "A hydrating and soothing serum to reduce inflammation",
          ingredients: "Niacinamide (4-5%), centella asiatica, or licorice root extract"
        },
        {
          type: "Moisturizer", 
          description: "A barrier-supporting moisturizer without potentially irritating fragrances",
          ingredients: "Ceramides, fatty acids, and cholesterol in a 3:1:1 ratio for optimal barrier repair"
        }
      ],
      
      furtherRecommendations: "I would recommend a follow-up analysis in 4-6 weeks after implementing these changes to assess improvement and potentially adjust your regimen. Pay close attention to how your skin responds to new products and introduce them one at a time with at least a week between additions."
    },
    ar: {
      summary: `بناءً على الصور المقدمة وتحليل الذكاء الاصطناعي، يمكنني أن أرى أن لديك بشرة مختلطة مع ${analysis.detectedIssues.join(', ')}. يبدو حاجز البشرة لديك متضررًا قليلاً، مع علامات التهاب خفيف في مناطق معينة.`,
      
      detailedAnalysis: `
        يبدو أن مشاكل البشرة الرئيسية لديك تتعلق بوظيفة حاجز الترطيب والالتهاب الخفيف.
        تشير الملمس غير المتساوي والبثور العرضية إلى مشاكل محتملة في تجدد الخلايا وربما بعض الانسداد البصيلي.
        
        ألاحظ أن مستوى ترطيب بشرتك أقل قليلاً من الأمثل، مما قد يساهم في زيادة إنتاج الزيت في منطقة T حيث تحاول البشرة تعويض الجفاف.
        
        نمط الاحمرار يتوافق مع الحساسية الخفيفة، التي من المحتمل أن تتفاقم بسبب العوامل البيئية بدلاً من حالة جلدية أساسية مثل الوردية. ومع ذلك، فإن رد فعل بشرتك ضمن النطاق الذي يمكن معالجته بفعالية باستخدام نظام العناية بالبشرة المناسب.
        
        تُظهر وظيفة الحاجز الواقي للبشرة تضررًا طفيفًا استنادًا إلى أنماط فقدان الماء عبر البشرة الواضحة في التحليل.
      `,
      
      possibleCauses: [
        "العوامل البيئية مثل المناخ والتلوث أو التغيرات في الطقس",
        "التقلبات الهرمونية النموذجية لفئتك العمرية",
        "تفاعل محتمل مع مكونات منتجات العناية بالبشرة الحالية",
        "عوامل نمط الحياة بما في ذلك التوتر وجودة النوم وأنماط النظام الغذائي",
        "احتمال المبالغة في التقشير أو استخدام منتجات قاسية جدًا لنوع بشرتك"
      ],
      
      recommendations: [
        "التركيز على إعادة بناء حاجز البشرة باستخدام منتجات غنية بالسيراميد",
        "إدخال التقشير الكيميائي اللطيف 2-3 مرات أسبوعيًا لمعالجة مشاكل الملمس",
        "النظر في دمج النياسيناميد للمساعدة في تنظيم إنتاج الزيت وتقليل الالتهاب",
        "ضمان الاستخدام المستمر للحماية من الأشعة فوق البنفسجية بعامل حماية +30 يوميًا",
        "تضمين مكونات مرطبة مثل حمض الهيالورونيك والجليسرين في روتينك"
      ],
      
      productSuggestions: [
        {
          type: "منظف",
          description: "منظف لطيف وغير مجرد مع درجة حموضة بين 4.5-5.5 للحفاظ على طبقة الحموضة في بشرتك",
          ingredients: "ابحث عن منظفات تحتوي على الجليسرين أو الألانتوين أو البانثينول"
        },
        {
          type: "علاج",
          description: "فكر في منتج PHA أو BHA للتقشير اللطيف وتنظيف المسام",
          ingredients: "جلوكونولاكتون (PHA) أو حمض الساليسيليك 2٪ (BHA)"
        },
        {
          type: "سيروم",
          description: "سيروم مرطب ومهدئ لتقليل الالتهاب",
          ingredients: "نياسيناميد (4-5٪)، سنتيلا آسياتيكا، أو مستخلص جذر العرقسوس"
        },
        {
          type: "مرطب", 
          description: "مرطب داعم للحاجز بدون عطور مهيجة محتملة",
          ingredients: "سيراميد، أحماض دهنية، وكوليسترول بنسبة 3:1:1 لإصلاح الحاجز الأمثل"
        }
      ],
      
      furtherRecommendations: "أوصي بتحليل متابعة في 4-6 أسابيع بعد تنفيذ هذه التغييرات لتقييم التحسن وتعديل نظامك المحتمل. انتبه جيدًا إلى كيفية استجابة بشرتك للمنتجات الجديدة وقدمها واحدة تلو الأخرى مع أسبوع على الأقل بين الإضافات."
    }
  };

  return (
    <div className="space-y-6">
      <Tabs defaultValue="analysis" dir={language === 'ar' ? 'rtl' : 'ltr'}>
        <TabsList className="mb-4">
          <TabsTrigger value="analysis" className="flex items-center gap-2">
            <FileText className="h-4 w-4" />
            {language === 'ar' ? 'تحليل الطبيب' : 'Doctor Analysis'}
          </TabsTrigger>
          <TabsTrigger value="chat" className="flex items-center gap-2">
            <MessageSquare className="h-4 w-4" />
            {language === 'ar' ? 'استشارة مباشرة' : 'Live Consultation'}
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="analysis" className="space-y-6">
          <div className={language === 'ar' ? 'text-right' : ''}>
            <h3 className="text-xl font-medium mb-4 text-primary">
              {language === 'ar' ? 'تحليل الطبيب' : 'Dermatologist Analysis'}
            </h3>
            
            <div className="prose max-w-none">
              <p className="text-lg font-medium mb-4">
                {language === 'ar' ? doctorAnalysis.ar.summary : doctorAnalysis.en.summary}
              </p>
              
              <h4 className="text-lg font-medium mt-6 mb-3">
                {language === 'ar' ? 'تقييم سريري مفصل' : 'Detailed Clinical Assessment'}
              </h4>
              <p className="whitespace-pre-line text-gray-700">
                {language === 'ar' ? doctorAnalysis.ar.detailedAnalysis : doctorAnalysis.en.detailedAnalysis}
              </p>
              
              <h4 className="text-lg font-medium mt-6 mb-3">
                {language === 'ar' ? 'العوامل المساهمة المحتملة' : 'Potential Contributing Factors'}
              </h4>
              <ul className="list-disc pl-5 space-y-2 text-gray-700">
                {(language === 'ar' ? doctorAnalysis.ar.possibleCauses : doctorAnalysis.en.possibleCauses).map((cause, index) => (
                  <li key={index}>{cause}</li>
                ))}
              </ul>
              
              <h4 className="text-lg font-medium mt-6 mb-3">
                {language === 'ar' ? 'التوصيات السريرية' : 'Clinical Recommendations'}
              </h4>
              <ul className="list-disc pl-5 space-y-2 text-gray-700">
                {(language === 'ar' ? doctorAnalysis.ar.recommendations : doctorAnalysis.en.recommendations).map((rec, index) => (
                  <li key={index}>{rec}</li>
                ))}
              </ul>
              
              <h4 className="text-lg font-medium mt-6 mb-4">
                {language === 'ar' ? 'توصيات المنتج حسب الفئة' : 'Product Recommendations by Category'}
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {(language === 'ar' ? doctorAnalysis.ar.productSuggestions : doctorAnalysis.en.productSuggestions).map((product, index) => (
                  <Card key={index} className="bg-white">
                    <CardContent className="pt-4">
                      <Badge className="mb-2 bg-primary">{product.type}</Badge>
                      <p className="text-sm text-gray-700">{product.description}</p>
                      <p className="text-xs text-gray-500 mt-2">
                        <span className="font-medium">
                          {language === 'ar' ? 'المكونات الرئيسية:' : 'Key ingredients:'}
                        </span> {product.ingredients}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>
              
              <h4 className="text-lg font-medium mt-6 mb-3">
                {language === 'ar' ? 'متابعة الرعاية' : 'Follow-up Care'}
              </h4>
              <p className="text-gray-700">
                {language === 'ar' ? doctorAnalysis.ar.furtherRecommendations : doctorAnalysis.en.furtherRecommendations}
              </p>
              
              <div className="mt-8 p-4 bg-blue-50 rounded-lg border border-blue-100">
                <p className="text-sm text-blue-800">
                  <span className="font-medium">
                    {language === 'ar' ? 'إخلاء المسؤولية:' : 'Disclaimer:'}
                  </span> {' '}
                  {language === 'ar' 
                    ? 'تم إنشاء هذا التحليل بواسطة الذكاء الاصطناعي ويجب اعتباره معلومات تعليمية فقط. إنه ليس بديلاً عن استشارة شخصية مع طبيب جلدية معتمد.'
                    : 'This analysis is generated by an AI and should be considered as educational information only. It is not a replacement for an in-person consultation with a board-certified dermatologist.'
                  }
                </p>
              </div>
            </div>
          </div>
        </TabsContent>
        
        <TabsContent value="chat" className="h-[600px]">
          <AIDoctorChat analysisId={analysis.id} language={language} />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default DermatologistFeedback;
