
import React from 'react';
import { SkinAnalysis } from '@/types';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface DermatologistFeedbackProps {
  analysis: SkinAnalysis;
  premiumData: any;
}

const DermatologistFeedback: React.FC<DermatologistFeedbackProps> = ({ analysis, premiumData }) => {
  // Doctor's analysis would be generated by an AI in a real app
  const doctorAnalysis = {
    summary: `Based on the submitted images and AI analysis, I can see that you have combination skin with ${analysis.detectedIssues.join(', ')}. Your skin barrier appears slightly compromised, with signs of mild inflammation in certain areas.`,
    
    detailedAnalysis: `
      Your primary skin concerns appear to be related to moisture barrier function and mild inflammation. 
      The uneven texture and occasional breakouts suggest potential issues with cell turnover and possibly some follicular congestion.
      
      I notice that your skin's hydration level is slightly below optimal, which may be contributing to the increased oil production in the T-zone as the skin tries to compensate for the dehydration.
      
      The redness pattern is consistent with mild sensitivity, likely exacerbated by environmental factors rather than an underlying skin condition like rosacea. However, your skin's reaction is well within the range that can be effectively addressed with the right skincare regimen.
      
      Your skin's protective barrier function shows minor compromise based on the transepidermal water loss patterns evident in the analysis.
    `,
    
    possibleCauses: [
      "Environmental factors such as climate, pollution, or weather changes",
      "Hormonal fluctuations typical of your age demographic",
      "Potential reactivity to ingredients in current skincare products",
      "Lifestyle factors including stress, sleep quality, and dietary patterns",
      "Possible over-exfoliation or use of products that are too harsh for your skin type"
    ],
    
    recommendations: [
      "Focus on rebuilding your skin barrier with ceramide-rich products",
      "Introduce gentle chemical exfoliation 2-3 times weekly to address texture concerns",
      "Consider incorporating niacinamide to help regulate oil production and reduce inflammation",
      "Ensure consistent use of broad-spectrum SPF 30+ daily",
      "Include hydrating ingredients like hyaluronic acid and glycerin in your routine"
    ],
    
    productSuggestions: [
      {
        type: "Cleanser",
        description: "A gentle, non-stripping cleanser with a pH between 4.5-5.5 to maintain your skin's acid mantle",
        ingredients: "Look for cleansers containing glycerin, allantoin, or panthenol"
      },
      {
        type: "Treatment",
        description: "Consider a PHA or BHA product for gentle exfoliation and pore clearing",
        ingredients: "Gluconolactone (PHA) or 2% salicylic acid (BHA)"
      },
      {
        type: "Serum",
        description: "A hydrating and soothing serum to reduce inflammation",
        ingredients: "Niacinamide (4-5%), centella asiatica, or licorice root extract"
      },
      {
        type: "Moisturizer", 
        description: "A barrier-supporting moisturizer without potentially irritating fragrances",
        ingredients: "Ceramides, fatty acids, and cholesterol in a 3:1:1 ratio for optimal barrier repair"
      }
    ],
    
    furtherRecommendations: "I would recommend a follow-up analysis in 4-6 weeks after implementing these changes to assess improvement and potentially adjust your regimen. Pay close attention to how your skin responds to new products and introduce them one at a time with at least a week between additions."
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-xl font-medium mb-4 text-primary">Dermatologist Analysis</h3>
        
        <div className="prose max-w-none">
          <p className="text-lg font-medium mb-4">{doctorAnalysis.summary}</p>
          
          <h4 className="text-lg font-medium mt-6 mb-3">Detailed Clinical Assessment</h4>
          <p className="whitespace-pre-line text-gray-700">{doctorAnalysis.detailedAnalysis}</p>
          
          <h4 className="text-lg font-medium mt-6 mb-3">Potential Contributing Factors</h4>
          <ul className="list-disc pl-5 space-y-2 text-gray-700">
            {doctorAnalysis.possibleCauses.map((cause, index) => (
              <li key={index}>{cause}</li>
            ))}
          </ul>
          
          <h4 className="text-lg font-medium mt-6 mb-3">Clinical Recommendations</h4>
          <ul className="list-disc pl-5 space-y-2 text-gray-700">
            {doctorAnalysis.recommendations.map((rec, index) => (
              <li key={index}>{rec}</li>
            ))}
          </ul>
          
          <h4 className="text-lg font-medium mt-6 mb-4">Product Recommendations by Category</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {doctorAnalysis.productSuggestions.map((product, index) => (
              <Card key={index} className="bg-white">
                <CardContent className="pt-4">
                  <Badge className="mb-2 bg-primary">{product.type}</Badge>
                  <p className="text-sm text-gray-700">{product.description}</p>
                  <p className="text-xs text-gray-500 mt-2">
                    <span className="font-medium">Key ingredients:</span> {product.ingredients}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
          
          <h4 className="text-lg font-medium mt-6 mb-3">Follow-up Care</h4>
          <p className="text-gray-700">{doctorAnalysis.furtherRecommendations}</p>
          
          <div className="mt-8 p-4 bg-blue-50 rounded-lg border border-blue-100">
            <p className="text-sm text-blue-800">
              <span className="font-medium">Disclaimer:</span> This analysis is generated by an AI and should be considered as educational information only. It is not a replacement for an in-person consultation with a board-certified dermatologist.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DermatologistFeedback;
