// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpmymdccdlnnrswbsdhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwbXltZGNjZGxubnJzd2JzZGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0OTE1OTgsImV4cCI6MjA1NDA2NzU5OH0.brdOdYMzQexXDOTTASx_FYta8sXvXuZngPcxAxSpTcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);